# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Some Natalie's corner of the internet
email: no
description: >- # this means to ignore newlines until "baseurl:"
  Things I'm learning, working on, or thinking about.  All opinions and snark my own.
twitter_username: some_natalie
github_username: some-natalie
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - work-stuff/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-R78L1QDY79" # Replace this with your ID, or delete
    anonymize_ip: true

author:
  name: "Natalie Somersall"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Things I'm learning, working on, or thinking about.  All opinions and snark my own."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://some-natalie.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/some-natalie"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nsomersall"
    - label: "Sessionize"
      icon: "fas fa-fw fa-microphone"
      url: "https://sessionize.com/some-natalie/"
#    - label: "Twitter (not active))"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/some_natalie"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/some-natalie"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nsomersall"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 150
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
