apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path-pv
  namespace: devcontainers
  labels:
    usage: local-path-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: unique-volumeid # make sure this volumeid is unique in the cluster
    volumeAttributes:
      # resourceGroup: EXISTING_RESOURCE_GROUP_NAME  # optional, only set this when storage account is not in the same resource group as agent node
      shareName: devcontainers-cache
    nodeStageSecretRef:
      name: azure-secret
      namespace: devcontainers
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
