apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: devcontainers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      usage: local-path-pv
