# mcr.microsoft.com/devcontainers/python:3
apiVersion: v1
kind: Pod
metadata:
  name: python-devcontainer
  namespace: devcontainers
  labels:
    app: python-devcontainer
spec:
  containers:
    - image: mcr.microsoft.com/devcontainers/python:3
      imagePullPolicy: IfNotPresent
      name: python-devcontainer
      resources:
        limits:
          cpu: "4000m"
          memory: "4Gi"
        requests:
          cpu: "2000m"
          memory: "2Gi"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"] # keep container running forever
      volumeMounts:
        - mountPath: /home/vscode/code
          name: local-path-pvc
          readOnly: false
  volumes:
    - name: local-path-pvc
      persistentVolumeClaim:
        claimName: local-path-pvc
