issuer: https://token.actions.githubusercontent.com
subject: repo:some-natalie/kubernoodles:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: some-natalie/kubernoodles/.github/workflows/janky-dependabot.yml@.*

permissions:
  contents: write
