issuer: https://token.actions.githubusercontent.com
subject: repo:some-natalie/website:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: some-natalie/website/.github/workflows/update-readme.yml@.*

permissions:
  contents: write
