name: 🍋 Update kodi

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * 3"

jobs:
  updates:
    name: Update the OS and reboot the VM
    runs-on: kodi
    steps:
      - name: Update the apt cache
        shell: bash
        run: |
          sudo apt clean
          sudo apt update
      - name: Run all package updates
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt dist-upgrade -y
      - name: Reboot
        shell: bash
        run: sudo shutdown -r +1 "Rebooting ... brb"

  wait:
    name: wait 5 minutes
    runs-on: ubuntu-latest
    needs: [updates]
    steps:
      - name: sleep 300
        shell: bash
        run: sleep 300

  healthcheck:
    name: Verify everything is back up and online
    runs-on: kodi
    needs: [wait]
    steps:
      - name: Verify we're back online and have rebooted less than 10 minutes ago
        shell: bash
        run: |
          secs="$(awk '{print $1}' /proc/uptime | sed 's/\.[^\.]*$//')"
          if [ "$secs" -lt 600 ]; then
            echo "System rebooted less than 10 minutes ago"
            exit 0
          else
            echo "System rebooted more than 10 minutes ago"
            exit 1
          fi
      - name: Check Unifi controller is up and healthy
        shell: bash
        run: sudo docker ps -a | grep jacobalberty\/unifi\.*\(healthy\)

  create-failure-issue:
    name: Create an issue on failure of any step to investigate
    runs-on: ubuntu-latest # use GitHub hosted runners
    if: ${{ failure() }}
    permissions:
      contents: read
      issues: write
    steps:
      - name: Create failure issue
        shell: bash
        run: |
          gh issue create -R some-natalie/some-natalie \
            --title "Update on pihole failed" \
            --body "Please investigate!"
